import { BeverageSchema } from "../../models/beverage.schema";

export default defineEventHandler(async () => {
    const seedData = [
        {
            category: "Wine",
            subcategory: "Red Wine",
            name: "Terre de Mistral Reserve",
            producer: "Terre",
            country: "France",
            region: "Rhône Valley, Côtes du Rhône",
            year: 2023,
            volume: 750,
            alcohol_by_volume: 14.5,
            price: 9.0,
            description: "Spicy flavor with notes of blackberries, wild raspberries, black pepper, licorice, violets, and bay leaf. Serve at 16-18°C with lamb or beef dishes.",
            organic: true,
            vegan: false,
            shelf_amount: 50,
            shelf_id: 2167
        },
        {
            category: "Wine",
            subcategory: "Red Wine",
            name: "Nor'wester Pinot Noir",
            producer: "Greystone Wines",
            country: "New Zealand",
            region: "Canterbury, North Canterbury",
            year: 2023,
            volume: 750,
            alcohol_by_volume: 13.5,
            price: 18.0,
            description: "Nuanced, spicy aroma with barrel character, notes of sandalwood, strawberries, roasted nuts, minerals, raspberries, blood orange, and cocoa. Serve at about 16°C with vegetarian dishes or light meat dishes, or with mildly seasoned lamb dishes.",
            organic: false,
            vegan: false,
            shelf_amount: 40,
            shelf_id: 2774
        },
        {
            category: "Wine",
            subcategory: "White Wine",
            name: "Stoneleigh Sauvignon Blanc",
            producer: "Stoneleigh",
            country: "New Zealand",
            region: "Marlborough",
            year: 2023,
            volume: 750,
            alcohol_by_volume: 13,
            price: 11.0,
            description: "Aromatic, youthful, very fresh taste with notes of passion fruit, blackcurrant leaves, pear, and lime. Serve at 8-10°C with fish or seafood dishes, preferably salads.",
            organic: false,
            vegan: true,
            shelf_amount: 60,
            shelf_id: 6311
        },
        {
            category: "Wine",
            subcategory: "White Wine",
            name: "Soave Classico",
            producer: "Pieropan",
            country: "Italy",
            region: "Veneto, Soave Classico",
            year: 2023,
            volume: 750,
            alcohol_by_volume: 12,
            price: 13.4,
            description: "Fruity taste with notes of yellow pears, herbs, minerals, tangerine, and apples. Serve at 8-10°C with vegetarian dishes or fish and seafood dishes.",
            organic: false,
            vegan: true,
            shelf_amount: 50,
            shelf_id: 20108
        },
        {
            category: "Beer",
            subcategory: "Ale",
            name: "Pale Ale",
            producer: "Craft Breweries",
            country: "USA",
            region: "California",
            year: 2023,
            volume: 330,
            alcohol_by_volume: 5.5,
            price: 2.5,
            description: "A hoppy and refreshing beer.",
            organic: false,
            vegan: true,
            shelf_amount: 100,
            shelf_id: 2,
        },
        {
            category: "Beer",
            subcategory: "Sour Beer",
            name: "Mango Mango Mango",
            producer: "Dugges Stillwater Artisanal",
            country: "Sweden",
            region: "Dalarna",
            year: 2024,
            volume: 330,
            alcohol_by_volume: 4.5,
            price: 3.4,
            description: "Very fruity, sour taste with a distinct character of mango, hints of grapefruit, jasmine flowers, biscuits, and lemon. Serve at 6-8°C as an aperitif or social drink.",
            organic: false,
            vegan: true,
            shelf_amount: 60,
            shelf_id: 31828,
        },
        {
            category: "Cider",
            subcategory: "Sweet",
            name: "Briska Elderflower",
            producer: "Briska",
            country: "Sweden",
            region: "Skåne",
            year: 2024,
            volume: 330,
            alcohol_by_volume: 4.5,
            price: 15.5,
            description: "Floral, fruity, sweet taste with a distinct character of elderflower, hints of green apples, and lime. Serve at 6-8°C as a social drink or with fruit and berry desserts.",
            organic: false,
            vegan: false,
            shelf_amount: 70,
            shelf_id: 1812,
        },

        {
            category: "Mixed Drinks",
            subcategory: "Sweet",
            name: "Ginger Joe Ginger Beer",
            producer: "Ginger Joe",
            country: "United Kingdom",
            region: "England",
            year: 2024,
            volume: 330,
            alcohol_by_volume: 4,
            price: 23.5,
            description: "Spicy, sweet taste with a slight heat and a distinct character of ginger, hints of honey, and bitter orange. Serve at 6-8°C as a social drink, with sushi, or with mildly spiced Asian dishes.",
            organic: false,
            vegan: false,
            shelf_amount: 50,
            shelf_id: 88018,
        },
        {
            category: "Non-alcoholic",
            subcategory: "Spirits",
            name: "Non-Alcoholic Snaps",
            producer: "Skåne",
            country: "Sweden",
            region: "Skåne",
            year: 2024,
            volume: 350,
            alcohol_by_volume: 0.5,
            price: 69.0,
            description: "Spicy taste with slight sweetness, hints of caraway, anise, and dill. Serve chilled as a snaps.",
            organic: false,
            vegan: false,
            shelf_amount: 50,
            shelf_id: 1948,
        },

        {
            category: "Spirits",
            subcategory: "Bitter",
            name: "Mediterranean Citrus",
            producer: "Purity Spritz",
            country: "Sweden",
            region: "Dalarna",
            year: 2024,
            volume: 700,
            alcohol_by_volume: 30,
            price: 26.3,
            description: "Spicy, bitter taste with hints of grapefruit, bergamot, and orange peel. Serve at room temperature as a digestif or use as a cocktail ingredient.",
            organic: false,
            vegan: true,
            shelf_amount: 40,
            shelf_id: 84388,
        },
        {
            category: "Spirits",
            subcategory: "Bitter",
            name: "Aperitivo",
            producer: "Select",
            country: "Italy",
            region: "Lombardy",
            year: 2024,
            volume: 700,
            alcohol_by_volume: 17.5,
            price: 19.4,
            description: "Spicy, sweet, bitter taste with hints of wormwood, juniper, rhubarb, and blood orange. Serve well chilled as an aperitif or use as a cocktail ingredient.",
            organic: false,
            vegan: false,
            shelf_amount: 30,
            shelf_id: 85247,
        },
        {
            category: "Spirits",
            subcategory: "Tequila",
            name: "Silver",
            producer: "Patron",
            country: "Mexico",
            region: "Jalisco",
            year: 2024,
            volume: 700,
            alcohol_by_volume: 40,
            price: 45.6,
            description: "Nuanced, fruity, spicy taste with hints of pear, white pepper, citrus, agave, and fresh herbs. Used as a cocktail ingredient.",
            organic: false,
            vegan: true,
            shelf_amount: 50,
            shelf_id: 87094,
        },
        {
            category: "Spirits",
            subcategory: "Vodka",
            name: "Koskenkorva Vodka",
            producer: "Koskenkorva",
            country: "Finland",
            region: "Etela-Pohjanmaa",
            year: 2024,
            volume: 350,
            alcohol_by_volume: 37.5,
            price: 11.5,
            description: "Clean taste with notes of bread and a hint of straw. Serve chilled as a schnapps or use as a cocktail ingredient.",
            organic: false,
            vegan: true,
            shelf_amount: 100,
            shelf_id: 167
        },
        {
            category: "Spirits",
            subcategory: "Vodka",
            name: "Absolut Vodka",
            producer: "Absolut",
            country: "Sweden",
            region: "Skåne, Kristianstad Municipality",
            year: 2024,
            volume: 350,
            alcohol_by_volume: 40,
            price: 12.0,
            description: "Clean taste with notes of light bread and citrus. Serve chilled as a schnapps or use as a cocktail ingredient.",
            organic: false,
            vegan: true,
            shelf_amount: 100,
            shelf_id: 88
        },
        {
            category: "Non-Alcoholic",
            subcategory: "Wine",
            name: "Viva La Vida Sparkling",
            producer: "Viva Wines",
            country: "Spain",
            region: "Catalonia",
            year: 2022,
            volume: 750,
            alcohol_by_volume: 0.0,
            price: 12.50,
            description: "A crisp sparkling wine with fresh notes of green apple and citrus, balanced with a hint of floral undertones. Serve chilled with seafood or light appetizers.",
            organic: true,
            vegan: true,
            shelf_amount: 85,
            shelf_id: 4821
        },
        {
            category: "Non-Alcoholic",
            subcategory: "Beer",
            name: "HopAway IPA",
            producer: "Brewster Brewery",
            country: "Germany",
            region: "Bavaria",
            year: 2021,
            volume: 500,
            alcohol_by_volume: 0.0,
            price: 3.95,
            description: "A hoppy and refreshing IPA with aromas of pine, citrus, and a smooth malty backbone. Perfect for enjoying on a sunny afternoon.",
            organic: false,
            vegan: true,
            shelf_amount: 120,
            shelf_id: 8317
        },
        {
            category: "Non-Alcoholic",
            subcategory: "Cider",
            name: "Golden Orchard Cider",
            producer: "Green Apple Cider Co.",
            country: "England",
            region: "Somerset",
            year: 2020,
            volume: 330,
            alcohol_by_volume: 0.0,
            price: 2.75,
            description: "A light and crisp cider with a blend of sweet and tart apple flavors, offering a refreshing drink that pairs well with casual meals.",
            organic: true,
            vegan: true,
            shelf_amount: 150,
            shelf_id: 4261
        },
        {
            category: "Non-Alcoholic",
            subcategory: "Mixed Drinks",
            name: "Tropical Breeze",
            producer: "TropiMix",
            country: "USA",
            region: "California",
            year: 2022,
            volume: 250,
            alcohol_by_volume: 0.0,
            price: 4.50,
            description: "A vibrant blend of tropical fruits like mango, pineapple, and passion fruit, with a refreshing splash of lime. Perfect for a summer day.",
            organic: true,
            vegan: true,
            shelf_amount: 95,
            shelf_id: 7134
        },
        {
            category: "Non-Alcoholic",
            subcategory: "Spirits",
            name: "Zero Gin",
            producer: "Pure Spirit Distillery",
            country: "Scotland",
            region: "Edinburgh",
            year: 2023,
            volume: 700,
            alcohol_by_volume: 0.0,
            price: 22.99,
            description: "A non-alcoholic gin with the aromatic notes of juniper, citrus, and a mix of botanicals, perfect for gin lovers seeking a zero-alcohol option.",
            organic: false,
            vegan: true,
            shelf_amount: 60,
            shelf_id: 1275
        },
        {
            category: "Non-Alcoholic",
            subcategory: "Wine",
            name: "Grape Garden Shiraz",
            producer: "Grape Garden Winery",
            country: "Australia",
            region: "Barossa Valley",
            year: 2021,
            volume: 750,
            alcohol_by_volume: 0.0,
            price: 14.99,
            description: "A rich and full-bodied red wine with notes of ripe berries, dark chocolate, and spices, offering a velvety smooth finish.",
            organic: true,
            vegan: true,
            shelf_amount: 110,
            shelf_id: 4928
        },
        {
            category: "Non-Alcoholic",
            subcategory: "Beer",
            name: "Citrus Hops Lager",
            producer: "Summit Brewing",
            country: "USA",
            region: "Colorado",
            year: 2021,
            volume: 330,
            alcohol_by_volume: 0.0,
            price: 3.50,
            description: "A light and zesty lager with citrusy hop notes and a crisp, clean finish. A refreshing choice for beer lovers who prefer a non-alcoholic option.",
            organic: true,
            vegan: true,
            shelf_amount: 145,
            shelf_id: 2854
        },
        {
            category: "Non-Alcoholic",
            subcategory: "Cider",
            name: "Apple Orchard Sparkler",
            producer: "Sparkling Orchard",
            country: "Ireland",
            region: "County Cork",
            year: 2020,
            volume: 500,
            alcohol_by_volume: 0.0,
            price: 4.20,
            description: "A sparkling cider made from a blend of Irish apples, offering a perfect balance of sweet and tart flavors with a crisp finish.",
            organic: false,
            vegan: true,
            shelf_amount: 80,
            shelf_id: 6359
        },
        {
            category: "Non-Alcoholic",
            subcategory: "Mixed Drinks",
            name: "Berry Fusion",
            producer: "Fusion Beverages",
            country: "Canada",
            region: "Ontario",
            year: 2022,
            volume: 330,
            alcohol_by_volume: 0.0,
            price: 3.00,
            description: "A sweet and tangy blend of mixed berries, including blueberry, raspberry, and strawberry, with a hint of mint for added refreshment.",
            organic: true,
            vegan: true,
            shelf_amount: 100,
            shelf_id: 2984
        },
        {
            category: "Non-Alcoholic",
            subcategory: "Spirits",
            name: "Mocktail Vodka",
            producer: "Mocktail Distillers",
            country: "Sweden",
            region: "Stockholm",
            year: 2023,
            volume: 700,
            alcohol_by_volume: 0.0,
            price: 24.99,
            description: "A non-alcoholic spirit with the smooth flavor of vodka and a mix of refreshing citrus and herbal notes, ideal for mocktail creations.",
            organic: true,
            vegan: true,
            shelf_amount: 55,
            shelf_id: 5603
        }
        // Add more posts
    ];

    try {
        // Empty database before adding new data
        await BeverageSchema.deleteMany({});
        console.log('Existing data cleared.');

        // Add new data
        await BeverageSchema.insertMany(seedData);
        console.log('Seed data successfully inserted.');

        return { message: 'Database seeded successfully' };
    } catch (error) {
        console.error('Error seeding database:', error);
        throw createError({
            statusCode: 500,
            message: 'Failed to seed database',
        });
    }
});
